language: node_js
sudo: true
dist: trusty
node_js:
    - 6.9.1
branches:
  only:
  - master
before_script:
    - ng set --global warnings.packageDeprecation=false
    - git init
script:
    - ng build --prod

